/*
  Implementing Cuckoo filter as a command interface to redis cli.
*/
#include <math.h>
//#include <assert.h>
#include <stdio.h>
#include <sys/types.h>
#include <string.h>
#include <stdlib.h>

/********************  FUNCTIONS NOT EXPOSED TO EXTERNAL SOURCES  *************************/

#define MAX_CUCKOO_FILTER_NAME_LENGTH 32+1
#define __MAX_SUM_OF_BITS_OF_ALL_CUCKOO_FILTERS ((512*1024*1024*8)-1)//Max of 4 billion entries are allowed. This is the requirement for testing with 4 billion entries.


/*
    m_bit_array_length_type. This can be a maximum of 512*1024*1024 bytes which requires atleast 29 bits for storage and hence can be stored in 32 bits(nearest power of 2). Hence the type of this variable is int (which uses 32 bits).
*/
/* Instead of using the following logic better use the already existing helpful functions..
#if (pow(2,sizeof(unsigned int)) >= __MAX_SUM_OF_BITS_OF_ALL_CUCKOO_FILTERS)

    #define M_BIT_ARRAY_LENGTH_TYPE unsigned int

#elif (pow(2,sizeof(unsigned long int)) >= __MAX_SUM_OF_BITS_OF_ALL_CUCKOO_FILTERS)

    #define M_BIT_ARRAY_LENGTH_TYPE unsigned long int

#else
   #define M_BIT_ARRAY_LENGTH_TYPE unsigned long long

#endif
*/
//The above code is logically simplified as the follwoing.
#define M_BIT_ARRAY_LENGTH_TYPE u_int32_t

/*
    m_bit_array_id_type. There can be a maximum of 512*1024*1024 cuckoo filters (assuming that 1bit is allocated for each cuckoo filter. The number of allowed cuckoo filters is based on the amount of memory utilized by the cuckoo filters.The total memory that can be utilized is given by MAX_SUM_OF_BITS_OF_ALL_CUCKOO_FILTERS constant). This count requires atleast 29 bits for storage and hence can be stored in 32 bits(nearest power of 2). Hence the type of this variable is int (which uses 32 bits).
*/
#define M_BIT_ARRAY_ID_TYPE M_BIT_ARRAY_LENGTH_TYPE


/*
    m_bit_array_content_type. This specifies the type of the value that can be stored in the m_bit_array. This is usually the type of the 'finger print' [ usually the char pointer (char *), because it can contain both alphabets and numeric values.
*/
#define FINGER_PRINT_TYPE char* 


/*
    The internal structure that holds the information about all the cuckoo filters.
*/
struct __cuckoo_filter
{
   char __name[MAX_CUCKOO_FILTER_NAME_LENGTH];//name of the filter.
   M_BIT_ARRAY_ID_TYPE __id;//This ID is autogenerated by the cuckoo_filter_creation function.
   FINGER_PRINT_TYPE * __m_bit_finger_print_array;//The internal m_bit_array that contains the finger-print of the given keys.
 
// TO DO :- ADD PLACEHOLDER FOR STORING THE ACTUAL VALUES, FOR TESTING THE PERFORMANCE AND FALSE POSITIVE PROBABILITIES.

   M_BIT_ARRAY_LENGTH_TYPE __m_bit_arr_len_in_bytes;//length of the m_bit_array.

   struct __cuckoo_filter* next;
};


/*
    The internal array that holds the list of all the available cuckoo filters.
*/
struct __cuckoo_filter *__cuckoo_filter_list = NULL;


/*
    Function Returns the finger-print for the given input value.
    NOTE :- This API is not exposed to outside world..
    Input : key - Integer for which finger-print is generated.
    Output : Finger-Print for given key..
*/
//M_BIT_ARRAY_CONTENT_TYPE __get_finger_print(int key)
FINGER_PRINT_TYPE __get_finger_print(const char* key)
{
  return 0;
}//end of get_finger_print function


/*
    Function Returns the first hash value for given key.
    Input : key -- The key for which hash value is returned.
    Output :
        The first hash value which is the index to the m_bit_array.
*/
M_BIT_ARRAY_LENGTH_TYPE __get_hash_1(const char* key, M_BIT_ARRAY_LENGTH_TYPE max_hash_value_limit)
{
    return 0;
}


/*
    Function returns the second hash value for the given key and first hash value.
    Input : key -- The key for which first hash value is to be returned.
            hash1 -- The first hash value using which the second hash value is calculated.
    Output :
        The second hash value which is also the index to the m_bit_array.
*/
M_BIT_ARRAY_LENGTH_TYPE __get_hash_2(FINGER_PRINT_TYPE finger_print, M_BIT_ARRAY_LENGTH_TYPE hash1, M_BIT_ARRAY_LENGTH_TYPE max_hash_value_limit)
{
    //return hash1 XOR __get_hash_1(finger_print)
    return 0;
}


/*
    Function that creates a new cuckoo filter and adds it into the cuckoo_filter_vector.
    Input : name - Cuckoo filter Name.
            m    - no of bits in the array.
    Output : 1 - If cuckoo filter is created successfully.
             0 - If cuckoo filter creation fails.
*/
short __create_cuckoo_filter(const char* __name, const int m_bit_size)
{
    //Check if the cuckoo filter can be created.
    //The max number of cuckoo filters that can be created depends on the amount of memory already allocated.
    //i.e. the total memory utilized by all cuckoo filters must not exceed 512MB (because my machine has RAM of 1GB only.
    //So if utilized memory is greater than 512MB, dont allocate/create any more filter.
    static M_BIT_ARRAY_LENGTH_TYPE cuckoo_filters_count = 1;
    static M_BIT_ARRAY_LENGTH_TYPE total_bits_in_all_filters = 0;
    //float val = (float)m_bit_size;

    if((total_bits_in_all_filters + m_bit_size) > __MAX_SUM_OF_BITS_OF_ALL_CUCKOO_FILTERS)
        return 0;

    //Create cuckoo_filter_structure.
    struct __cuckoo_filter *new_filter = (struct __cuckoo_filter *)malloc(sizeof(struct __cuckoo_filter));

    if(NULL == new_filter)
        return 0;

    strncpy(new_filter->__name,__name,MAX_CUCKOO_FILTER_NAME_LENGTH);
    new_filter->__name[MAX_CUCKOO_FILTER_NAME_LENGTH-1] = '\0';
    new_filter->__id = cuckoo_filters_count;
    new_filter->__m_bit_finger_print_array = NULL;
    //new_filter->__m_bit_arr_len_in_bytes = ceil((float)(m_bit_size)/8.0);

    //ceil((float)(m_bit_size)/8.0);
    new_filter->next = NULL;
    int afl = ceil((float)(1.0)/2.0);
 
    //Allocate 'n' pointers and assign..
    new_filter->__m_bit_finger_print_array =  (FINGER_PRINT_TYPE *)malloc(sizeof(FINGER_PRINT_TYPE) * new_filter->__m_bit_arr_len_in_bytes);
    
    //TO DO :- memset to all these allocated memory pointers is required.
    if(NULL == new_filter->__m_bit_finger_print_array)
        return 0;

    //We were successfully able to allocate memory to the cuckoo filter, now increment the necessary parameters and add into the cuckoo filters list.
    cuckoo_filters_count++;
    total_bits_in_all_filters+=m_bit_size;

    //Add it to the array.
    if(NULL == __cuckoo_filter_list)
        __cuckoo_filter_list = new_filter;
    else
        __cuckoo_filter_list -> next = new_filter;

    return 1;//Return Success..

}


/*
    Function that deletes the specified cuckoo filter.
    Input : name -- Name of the cuckoo filter to be deleted.
    Output : 
            Returns 0 if cuckoo filter deletion fails.
            Returns 1 if the cuckoo filter is deleted.
*/
short __delete_cuckoo_filter(const char* __name)
{
    //Remove the cuckoo_filter_structure from the array

    //De-allocate memory allocated for that cuckoo filter.
    //Free finger-print array (of all the pointers)
    //Free the cuckoo_filter.
}


/*********************** API'S VISIBLE TO EXTERNAL SOURCES **************/


/*
    Function adds a new cuckoo filter.
    Input : m - no of bits in the cuckoo-filter.
            name - name of the cuckoo filter.
    Output :
        Returns 0 if cuckoo filter creation fails.
        Returns 1 if cuckoo filter creation is successful.
*/
short add_cuckoo_filter(const char* name,const unsigned int m_bit_array_length_in_bits)
{
    if(NULL == name || m_bit_array_length_in_bits <= 0 
        || (strnlen(name,MAX_CUCKOO_FILTER_NAME_LENGTH-1)
        >= (MAX_CUCKOO_FILTER_NAME_LENGTH-1))
      ) 
        return 0;
    
    return __create_cuckoo_filter(name,m_bit_array_length_in_bits);

}//end of add_cuckoo_filter function.


/*
    Function to insert values into cuckoo filter.
    Input : key -- The item to be inserted into the cuckoo filter.
            name -- The name of the cuckoo filter.
    Output :
        Returns 0 -- insertion is successful
        Returns 1 -- insertion fails.
*/
//unsigned short insert_element(const char* name, const int key)
short insert_element(const char* name,const char* key)
{
    return 0;
}


/*
    Function to check if a key is present in the cuckoo filter set.
    Input : name -- cuckoo filter in which the key is to be checked.
             key -- The key to be checked for.
    Output : 
        Returns 0 -- if the key is not found.
        Returns 1 -- if the key is found in the cuckoo filter 'name'
*/
//unsigned short is_member(const char* name, const int key)
short is_member(const char* name, const char* key)
{
    return 0;
}


/*
    Function to delete the key from cuckoo filter.
    Input : key -- The key to be deleted from the cuckoo filter.
            name -- The name of cuckoo filter from which the key is to be deleted.
    Output : 
            Returns 0 -- if key deletion fails.
            Returns 1 -- if the key is deleted successfully.
*/
short delete_element(const char* name, const char* key)
{
    return 0;
}


/*
    Function to remove cuckoo filter.
    Input : name -- Name of the cuckoo filter to be deleted.
    Output : 
        Return 0 -- if cuckoo filter is deleted successfully.
        Return 1 -- if cuckoo filter deletion fails.
*/
short remove_cuckoo_filter(const char* name)
{
    return 0;
}
