/*
  Implementing Cuckoo filter as a command interface to redis cli.
*/

#define __MAX_NO_OF_BITS_IN_A_CUCKOO_FILTER 512*1024*1024*8//Max of 4 billion entries are allowed. This is the requirement for testing with 4 billion entries.

//#define __MAX_ALLOWED_CUCKOO_FILTERS pow(2,sizeof(int))-1

//#define __CUCKOO_BIT_ARRAY_TYPE unsigned short //becacuse we will store only 0 or 1.

/*
    Function Returns the finger-print for the given input value.
    NOTE :- This API is not exposed to outside world..
    Input : key - Integer for which finger-print is generated.
    Output : Finger-Print for given key..
*/
unsigned int __get_finger_print(int key)
{
    return 0;
}//end of get_finger_print function


/*
    The internal structure that holds the information about the different cuckoo filters.
*/
struct __cuckoo_filter
{
   char __name[32];//name of the filter.
   unsigned int __id;//MAX of 2^sizeof(int) cuckoo filters are allowed.This ID is autogenerated by the cuckoo_filter_creation function.
   unsigned short * __m_bit_array;//The internal m_bit_array.
   unsigned int __m_bit_array_len_in_bytes;//length of the m_bit_array.
};


/*
    The internal array that holds the list of all the available cuckoo filters.
*/
struct __cuckoo_filter cuckoo_filter_vector[__MAX_ALLOWED_CUCKOO_FILTER];


/*
    Function that creates a new cuckoo filter and adds it into the cuckoo_filter_vector.
    Input : name - Cuckoo filter Name.
            m    - no of bits in the array.
    Output : 1 - If cuckoo filter is created successfully.
             0 - If cuckoo filter creation fails.
*/
unsigned short __create_cuckoo_filter(const char* __name, const int m)
{
    //Check if the cuckoo filter can be created.
    //The max number of cuckoo filters that can be created depends on the amount of memory already allocated.
    //i.e. the total memory utilized by all cuckoo filters must not exceed 512MB (because my machine has RAM of 1GB only.

    //So if utilized memory is greater than 512MB, don't allocate/create any more filters.
    //if()

    //Create cuckoo_filter_structure.

    //Add it to the array.

}


/*
    Function that deletes the specified cuckoo filter.
*/
unsigned short __delete_cuckoo_filter(const char* __name)
{
    //Remove the cuckoo_filter_structure from the array

    //De-allocate memory allocated for that cuckoo filter.
}

/*

    Function to get hash of 1st function..
    Input :-
*/


/*
    Function creates a cuckoo filter.
    Input : m - no of bits in the cuckoo-filter.
    Output :
        Returns 0 if cuckoo filter creation fails.
        Returns 1 if cuckoo filter creation is successful.
*/
unsigned short create_cuckoo_filter(unsigned int m_bits)
{

   return 0; 
}//end of create_cuckoo_filter function.


/*
    Function to insert values into cuckoo filter.
    Input : key -- The item to be inserted into the cuckoo filter.
    Output :
        Returns 0 -- insertion is successful
        Returns 1 -- insertion fails.
*/
unsigned short insert_element(int key)
{
    return 0;
}



